package lpgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/HazelnutParadise/insyra/internal/utils"
)

type LPModel struct {
	Objective     string   // 目標函數
	ObjectiveType string   // 目標函數類型（Maximize or Minimize）
	Constraints   []string // 約束條件
	Bounds        []string // 變數邊界
	BinaryVars    []string // 二進制變數
	IntegerVars   []string // 整數變數
}

func NewLPModel() *LPModel {
	return &LPModel{}
}

// set objective
func (lp *LPModel) SetObjective(objType, obj string) *LPModel {
	lp.ObjectiveType = objType
	lp.Objective = obj
	return lp
}

// add constraint
func (lp *LPModel) AddConstraint(constr string) *LPModel {
	lp.Constraints = append(lp.Constraints, constr)
	return lp
}

// add bound
func (lp *LPModel) AddBound(bound string) *LPModel {
	lp.Bounds = append(lp.Bounds, bound)
	return lp
}

// add binary var
func (lp *LPModel) AddBinaryVar(varName string) *LPModel {
	// 確保變數不會同時是整數和二進制
	for i, intVar := range lp.IntegerVars {
		if intVar == varName {
			lp.IntegerVars = append(lp.IntegerVars[:i], lp.IntegerVars[i+1:]...)
			break
		}
	}
	lp.BinaryVars = append(lp.BinaryVars, varName)
	return lp
}

// add integer var
func (lp *LPModel) AddIntegerVar(varName string) *LPModel {
	// 確保變數不會同時是整數和二進制
	for i, binVar := range lp.BinaryVars {
		if binVar == varName {
			lp.BinaryVars = append(lp.BinaryVars[:i], lp.BinaryVars[i+1:]...)
			break
		}
	}
	lp.IntegerVars = append(lp.IntegerVars, varName)
	return lp
}

// WriteLP writes the model in CPLEX LP format, the same text GenerateLPFile
// saves. An objective type other than min/minimize/minimum or
// max/maximize/maximum (any case) is an error; the banner has been written by
// then.
func (lp *LPModel) WriteLP(w io.Writer) error {
	// 寫入行銷內容
	if _, err := io.WriteString(w, "\\Generated by Insyra.\n\\Visit https://insyra.hazelnut-paradise.com for more information.\n\n"); err != nil {
		return err
	}

	// 以大小寫不敏感方式辨識目標型別，未知的型別回報錯誤，而非靜默當成 MAX。
	var sense string
	switch strings.ToLower(strings.TrimSpace(lp.ObjectiveType)) {
	case "minimize", "min", "minimum":
		sense = "MIN"
	case "maximize", "max", "maximum":
		sense = "MAX"
	default:
		return fmt.Errorf("unknown ObjectiveType %q (expected Minimize/Maximize)", lp.ObjectiveType)
	}

	var b strings.Builder
	b.WriteString(sense + "\n")
	b.WriteString("  obj: " + lp.Objective + "\n")
	b.WriteString("Subject To\n")
	for i, constr := range lp.Constraints {
		fmt.Fprintf(&b, "  c%d: %s\n", i+1, constr)
	}
	section := func(head string, lines []string) {
		if len(lines) == 0 {
			return
		}
		b.WriteString(head + "\n")
		for _, line := range lines {
			b.WriteString("  " + line + "\n")
		}
	}
	section("Bounds", lp.Bounds)
	section("General", lp.IntegerVars)
	section("Binary", lp.BinaryVars)
	b.WriteString("End\n")

	_, err := io.WriteString(w, b.String())
	return err
}

// GenerateLPFile saves the model as a CPLEX LP file, with exactly the text
// WriteLP writes. It writes to a temporary file in the same directory that
// replaces filename only once the whole model is written, so a failed call
// leaves no file behind and an existing file at filename unchanged. It returns
// an error when the file cannot be created or written, or when WriteLP refuses
// the objective type.
func (lp *LPModel) GenerateLPFile(filename string) error {
	if err := utils.WriteFileAtomically(filename, lp.WriteLP); err != nil {
		return fmt.Errorf("failed to save LP file %s: %w", filename, err)
	}
	return nil
}
