package stats_test

import (
	"math"
	"os"
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/HazelnutParadise/insyra"
	"github.com/HazelnutParadise/insyra/stats"
)

// loadF64s reads a labelled comma-separated array out of
// testdata/ttest_data_dump.txt — produced by ttest_data_dump.R so that test
// inputs and the R reference values come from byte-identical data.
var (
	loadF64sOnce  sync.Once
	loadF64sCache map[string][]float64
)

func loadF64s(t *testing.T, label string) []float64 {
	t.Helper()
	loadF64sOnce.Do(func() {
		loadF64sCache = map[string][]float64{}
		raw, err := os.ReadFile("testdata/ttest_data_dump.txt")
		if err != nil {
			t.Fatalf("read testdata/ttest_data_dump.txt: %v", err)
		}
		for _, line := range strings.Split(string(raw), "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			i := strings.IndexByte(line, ':')
			if i < 0 {
				continue
			}
			name := line[:i]
			parts := strings.Split(line[i+1:], ",")
			vals := make([]float64, 0, len(parts))
			for _, p := range parts {
				p = strings.TrimSpace(p)
				if p == "" {
					continue
				}
				v, err := strconv.ParseFloat(p, 64)
				if err != nil {
					t.Fatalf("parse %s value %q: %v", name, p, err)
				}
				vals = append(vals, v)
			}
			loadF64sCache[name] = vals
		}
	})
	v, ok := loadF64sCache[label]
	if !ok {
		t.Fatalf("loadF64s: label %q not found in testdata/ttest_data_dump.txt", label)
	}
	return v
}

// Reference values generated by stats/testdata/ttest_reference.R using R 4.5.1's
// t.test() (the mainstream library for Student's t-tests). Cohen's d is computed
// in R using the same formula insyra uses (see ttest_reference.R header).
//
// Tolerances (chosen empirically — distuv vs R's pt/qt implementations of the
// Student's t CDF/quantile produce results that agree to roughly 1e-12 .. 1e-14
// in this range; CI bounds and p-values inherit that error):
//   tolStat = 1e-12   (t statistic, mean, mean diff, Cohen's d)
//   tolP    = 1e-12   (p-value)
//   tolCI   = 1e-10   (CI bounds, multiplied by t-quantile)
//   df is exact match for integer-valued, 1e-12 for Welch.
const (
	tolStat = 1e-12
	tolP    = 1e-12
	tolCI   = 1e-10
)

func tEqualOrNaNInf(a, b, tol float64) bool {
	if math.IsNaN(a) && math.IsNaN(b) {
		return true
	}
	if math.IsInf(a, 0) && math.IsInf(b, 0) && math.Signbit(a) == math.Signbit(b) {
		return true
	}
	if math.IsNaN(a) != math.IsNaN(b) || math.IsInf(a, 0) != math.IsInf(b, 0) {
		return false
	}
	if b == 0 {
		return math.Abs(a) <= tol
	}
	return math.Abs(a-b) <= tol*math.Max(1, math.Abs(b))
}

type singleTCase struct {
	name string
	data []float64
	mu   float64
	cl   float64 // 0 means use default 0.95
	t    float64
	p    float64
	df   float64
	ciLo float64
	ciHi float64
	mean float64
	n    int
	d    float64
}

func TestSingleSampleTTest_R(t *testing.T) {
	cases := []singleTCase{
		{
			name: "single1",
			data: []float64{52.12, 58.36, 57.49, 51.31, 61.25, 42.88, 46.89, 59.45, 56.20, 44.39, 48.15, 50.99, 56.84, 47.90, 49.78},
			mu:   50,
			t:    1.5366517223350304,
			p:    0.14666714679974524,
			df:   14,
			ciLo: 49.10295922277929,
			ciHi: 55.430374110554041,
			mean: 52.266666666666666,
			n:    15,
			d:    0.39676176863496787,
		},
		{
			name: "single2",
			data: []float64{49.55, 42.01, 50.22, 52.88, 42.75, 47.36, 54.17, 41.29, 45.63, 47.48, 55.81, 44.10, 43.75, 46.52, 50.94, 53.60, 43.07, 48.77, 46.82, 50.90},
			mu:   50,
			t:    -2.1927839016234536,
			p:    0.040972523801649008,
			df:   19,
			ciLo: 45.858403077427006,
			ciHi: 49.903596922572994,
			mean: 47.881,
			n:    20,
			d:    -0.49032138639972539,
		},
		{
			name: "small_data_large_diff",
			data: []float64{12, 14, 15, 11, 13},
			mu:   10,
			t:    4.2426406871192848,
			p:    0.013235599563682695,
			df:   4,
			ciLo: 11.036756838522443,
			ciHi: 14.963243161477557,
			mean: 13,
			n:    5,
			d:    1.8973665961010275,
		},
		{
			name: "large_data_small_diff",
			data: []float64{9.8, 10.1, 9.9, 10.2, 9.7, 10.0, 10.3, 9.6, 10.4, 10.0,
				9.9, 10.1, 9.8, 10.2, 10.0, 9.7, 10.3, 9.6, 10.4, 9.9},
			mu:   10,
			t:    -0.088625534269287806,
			p:    0.93030700778245523,
			df:   19,
			ciLo: 9.8769175494023536,
			ciHi: 10.113082450597645,
			mean: 9.9949999999999992,
			n:    20,
			d:    -0.019817271916836469,
		},
		{
			name: "data_with_negative_values",
			data: []float64{-5, -2, -6, -3, -4},
			mu:   0,
			t:    -5.6568542494923797,
			p:    0.0048126783300442271,
			df:   4,
			ciLo: -5.9632431614775578,
			ciHi: -2.0367568385224426,
			mean: -4,
			n:    5,
			d:    -2.5298221281347035,
		},
		{
			name: "data_very_close_to_mu",
			data: []float64{10.01, 9.99, 10.02, 9.98, 10.00},
			mu:   10,
			t:    0,
			p:    1,
			df:   4,
			ciLo: 9.9803675683852244,
			ciHi: 10.019632431614776,
			mean: 10,
			n:    5,
			d:    0,
		},
		// ---- Diverse cases (per CLAUDE.md gonum-priority refactor) ----
		{
			name: "minN", data: []float64{7, 9}, mu: 5,
			t: 3, p: 0.20483276469913345, df: 1,
			ciLo: -4.7062047361746941, ciHi: 20.706204736174694,
			mean: 8, n: 2, d: 2.1213203435596424,
		},
		{
			name: "largeN", data: loadF64s(t, "singleA_largeN"), mu: 5,
			t: 0.31223251776446431, p: 0.75552050352018763, df: 99,
			ciLo: 4.6517740159625927, ciHi: 5.4782839840374074,
			mean: 5.065029, n: 100, d: 0.031223251776446435,
		},
		{
			name: "huge_magnitude",
			data: []float64{1.0e9, 1.05e9, 0.97e9, 1.02e9, 0.99e9, 1.01e9}, mu: 1.0e9,
			t: 0.59761430466719334, p: 0.5761317257177424, df: 5,
			ciLo: 977990625.77584672, ciHi: 1035342707.5574865,
			mean: 1006666666.6666666, n: 6, d: 0.24397501823713186,
		},
		{
			name: "tiny_magnitude",
			data: []float64{1e-9, 2e-9, 1.5e-9, 0.5e-9, 1.2e-9}, mu: 0,
			t: 4.9560367552600759, p: 0.0077278878265963072, df: 4,
			ciLo: 5.4533365661760562e-10, ciHi: 1.9346663433823946e-09,
			mean: 1.2400000000000001e-09, n: 5, d: 2.2164070167498031,
		},
		{
			name: "cl99",
			data: []float64{20.1, 19.8, 20.5, 20.0, 19.9, 20.3, 20.2}, mu: 20, cl: 0.99,
			t: 1.2545000963743551, p: 0.25631545891582524, df: 6,
			ciLo: 19.776536788793774, ciHi: 20.452034639777654,
			mean: 20.114285714285714, n: 7, d: 0.47415646781615789,
		},
		{
			name: "cl90",
			data: []float64{20.1, 19.8, 20.5, 20.0, 19.9, 20.3, 20.2}, mu: 20, cl: 0.90,
			t: 1.2545000963743551, p: 0.25631545891582524, df: 6,
			ciLo: 19.937260820476272, ciHi: 20.291310608095156,
			mean: 20.114285714285714, n: 7, d: 0.47415646781615789,
		},
		{
			name: "heavy_skew_outlier",
			data: []float64{1, 2, 2, 3, 3, 3, 4, 4, 5, 100}, mu: 4,
			t: 0.89627239515580392, p: 0.39344870637033613, df: 9,
			ciLo: -9.2584664469367794, ciHi: 34.658466446936771,
			mean: 12.699999999999999, n: 10, d: 0.28342621726268047,
		},
		{
			name: "all_integers_with_ties",
			data: []float64{5, 5, 5, 6, 6, 6, 7, 7, 7, 8}, mu: 5,
			t: 3.6742346141747682, p: 0.0051210727642726269, df: 9,
			ciLo: 5.4611825644216401, ciHi: 6.9388174355783603,
			mean: 6.2000000000000002, n: 10, d: 1.1618950038622253,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			cl := c.cl
			if cl == 0 {
				cl = 0.95
			}
			dl := insyra.NewDataList(c.data)
			r, err := stats.SingleSampleTTest(dl, c.mu, cl)
			if err != nil {
				t.Fatalf("SingleSampleTTest error: %v", err)
			}
			if !tEqualOrNaNInf(r.Statistic, c.t, tolStat) {
				t.Errorf("t: got %.17g, want %.17g (Δ=%g)", r.Statistic, c.t, math.Abs(r.Statistic-c.t))
			}
			if !tEqualOrNaNInf(r.PValue, c.p, tolP) {
				t.Errorf("p: got %.17g, want %.17g (Δ=%g)", r.PValue, c.p, math.Abs(r.PValue-c.p))
			}
			if r.DF == nil || *r.DF != c.df {
				t.Errorf("df: got %v, want %v", r.DF, c.df)
			}
			if !tEqualOrNaNInf(r.CI[0], c.ciLo, tolCI) {
				t.Errorf("ci_lo: got %.17g, want %.17g (Δ=%g)", r.CI[0], c.ciLo, math.Abs(r.CI[0]-c.ciLo))
			}
			if !tEqualOrNaNInf(r.CI[1], c.ciHi, tolCI) {
				t.Errorf("ci_hi: got %.17g, want %.17g (Δ=%g)", r.CI[1], c.ciHi, math.Abs(r.CI[1]-c.ciHi))
			}
			if r.Mean == nil || !tEqualOrNaNInf(*r.Mean, c.mean, tolStat) {
				t.Errorf("mean: got %v, want %.17g", r.Mean, c.mean)
			}
			if r.N != c.n {
				t.Errorf("n: got %d, want %d", r.N, c.n)
			}
			if r.Mean2 != nil {
				t.Errorf("mean2 should be nil for single-sample, got %v", *r.Mean2)
			}
			if r.MeanDiff != nil {
				t.Errorf("meanDiff should be nil for single-sample, got %v", *r.MeanDiff)
			}
			if r.N2 != nil {
				t.Errorf("n2 should be nil for single-sample, got %v", *r.N2)
			}
			if len(r.EffectSizes) != 1 || r.EffectSizes[0].Type != "cohen_d" {
				t.Fatalf("expected one cohen_d effect size, got %+v", r.EffectSizes)
			}
			if !tEqualOrNaNInf(r.EffectSizes[0].Value, c.d, tolStat) {
				t.Errorf("cohen_d: got %.17g, want %.17g", r.EffectSizes[0].Value, c.d)
			}
		})
	}
}

func TestSingleSampleTTest_ConstantData(t *testing.T) {
	// Special cases R cannot test because t.test() errors on essentially constant data.
	// Tested against insyra's documented edge-case behavior (see ttest.go SingleSampleTTest).

	t.Run("data_equals_mu_constant", func(t *testing.T) {
		dl := insyra.NewDataList([]float64{50, 50, 50, 50, 50})
		r, err := stats.SingleSampleTTest(dl, 50, 0.95)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if !math.IsNaN(r.Statistic) {
			t.Errorf("expected NaN t, got %v", r.Statistic)
		}
		if !math.IsNaN(r.PValue) {
			t.Errorf("expected NaN p, got %v", r.PValue)
		}
		if r.DF == nil || *r.DF != 4 {
			t.Errorf("df: got %v, want 4", r.DF)
		}
		if r.CI[0] != 50 || r.CI[1] != 50 {
			t.Errorf("CI: got %v, want [50,50]", r.CI)
		}
		if r.Mean == nil || *r.Mean != 50 {
			t.Errorf("mean: got %v, want 50", r.Mean)
		}
		if len(r.EffectSizes) != 1 || r.EffectSizes[0].Value != 0 {
			t.Errorf("cohen_d: got %+v, want 0", r.EffectSizes)
		}
	})

	t.Run("constant_data_not_equal_mu", func(t *testing.T) {
		dl := insyra.NewDataList([]float64{10, 10, 10})
		r, err := stats.SingleSampleTTest(dl, 5, 0.95)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if !math.IsInf(r.Statistic, 1) {
			t.Errorf("expected +Inf t, got %v", r.Statistic)
		}
		if r.PValue != 0 {
			t.Errorf("expected p=0, got %v", r.PValue)
		}
		if r.DF == nil || *r.DF != 2 {
			t.Errorf("df: got %v, want 2", r.DF)
		}
		if r.CI[0] != 10 || r.CI[1] != 10 {
			t.Errorf("CI: got %v, want [10,10]", r.CI)
		}
		if len(r.EffectSizes) != 1 || !math.IsInf(r.EffectSizes[0].Value, 1) {
			t.Errorf("cohen_d: expected +Inf, got %+v", r.EffectSizes)
		}
	})
}

type twoTCase struct {
	name            string
	data1, data2    []float64
	equalVar        bool
	cl              float64 // 0 = use 0.95
	t, p, df        float64
	ciLo, ciHi      float64
	mean1, mean2, d float64
	n1, n2          int
}

func TestTwoSampleTTest_R(t *testing.T) {
	cases := []twoTCase{
		{
			name:     "equal_var_true_strong_diff",
			data1:    []float64{55.1, 49.3, 58.2, 61.9, 47.3, 51.0, 53.8, 59.7, 52.4, 56.1},
			data2:    []float64{46.9, 41.2, 45.7, 49.8, 44.0, 47.6, 46.5, 43.9, 48.3, 45.4},
			equalVar: true,
			t:        5.1337284407636394,
			p:        6.9572007526819179e-05,
			df:       18,
			ciLo:     5.051006305392165,
			ciHi:     12.04899369460783,
			mean1:    54.479999999999997,
			mean2:    45.93,
			d:        2.2958731543143003,
			n1:       10, n2: 10,
		},
		{
			name:     "equal_var_false_strong_diff",
			data1:    []float64{55.1, 49.3, 58.2, 61.9, 47.3, 51.0, 53.8, 59.7, 52.4, 56.1},
			data2:    []float64{46.9, 41.2, 45.7, 49.8, 44.0, 47.6, 46.5, 43.9, 48.3, 45.4},
			equalVar: false,
			t:        5.1337284407636394,
			p:        0.00016162670438298697,
			df:       13.729088042713139,
			ciLo:     4.9713275651457725,
			ciHi:     12.128672434854222,
			mean1:    54.479999999999997,
			mean2:    45.93,
			d:        2.2958731543142998,
			n1:       10, n2: 10,
		},
		{
			name:     "equal_var_true_small_diff",
			data1:    []float64{50.2, 48.5, 52.1, 51.3, 50.5, 49.9, 48.7, 50.8},
			data2:    []float64{47.9, 48.1, 49.5, 50.2, 48.8, 49.7, 48.9, 49.1},
			equalVar: true,
			t:        2.3881138762600416,
			p:        0.031579319583298508,
			df:       14,
			ciLo:     0.12481641209926291,
			ciHi:     2.3251835879007401,
			mean1:    50.25,
			mean2:    49.024999999999999,
			d:        1.1940569381300208,
			n1:       8, n2: 8,
		},
		{
			name:     "equal_var_false_small_diff",
			data1:    []float64{60.0, 59.5, 58.8, 60.2, 59.9},
			data2:    []float64{55.1, 52.3, 58.4, 53.6, 54.2, 53.1},
			equalVar: false,
			t:        5.7180955855558073,
			p:        0.0014105403530915289,
			df:       5.7781425741184229,
			ciLo:     2.9709600087297208,
			ciHi:     7.489039991270273,
			mean1:    59.68,
			mean2:    54.450000000000003,
			d:        3.3217230908149511,
			n1:       5, n2: 6,
		},
		{
			name:     "diff_sample_size_equal_var_small_diff",
			data1:    []float64{10.1, 10.3, 10.0, 9.9, 10.2},
			data2:    []float64{9.8, 9.7, 9.9, 10.0, 9.6, 9.5, 9.4},
			equalVar: true,
			t:        3.5043832202523144,
			p:        0.0056847288423440626,
			df:       10,
			ciLo:     0.14567406451331569,
			ciHi:     0.65432593548668494,
			mean1:    10.1,
			mean2:    9.6999999999999993,
			d:        2.0519567041703097,
			n1:       5, n2: 7,
		},
		{
			name:     "diff_sample_size_unequal_var_large_diff",
			data1:    []float64{100, 105, 98, 110, 102, 103},
			data2:    []float64{80, 85, 78, 90, 82},
			equalVar: false,
			t:        7.3854894587599631,
			p:        6.8150082538531799e-05,
			df:       8.1967213114754109,
			ciLo:     13.781302675690368,
			ciHi:     26.218697324309634,
			mean1:    103,
			mean2:    83,
			d:        4.4946657497549465,
			n1:       6, n2: 5,
		},
		{
			name:     "data_near_zero_equal_var",
			data1:    []float64{0.01, 0.02, 0.015, 0.025},
			data2:    []float64{-0.01, -0.005, -0.012, -0.008},
			equalVar: true,
			t:        7.3816862299899384,
			p:        0.00031704739746400142,
			df:       6,
			ciLo:     0.01754854154033272,
			ciHi:     0.034951458459667281,
			mean1:    0.017500000000000002,
			mean2:    -0.0087500000000000008,
			d:        5.2196403898172461,
			n1:       4, n2: 4,
		},
		{
			name:     "data_with_negative_values_unequal_var",
			data1:    []float64{-5, -4, -6, -3, -5},
			data2:    []float64{1, 2, 0, 3, 1, 2},
			equalVar: false,
			t:        -9.1614589900881871,
			p:        1.2548343809075323e-05,
			df:       8.3203198494825941,
			ciLo:     -7.6251847315420562,
			ciHi:     -4.574815268457944,
			mean1:    -4.5999999999999996,
			mean2:    1.5,
			d:        -5.5685126679691876,
			n1:       5, n2: 6,
		},
		{
			name:     "data_with_duplicates_equal_var",
			data1:    []float64{10, 12, 10, 11, 12, 10},
			data2:    []float64{8, 9, 8, 7, 9, 8},
			equalVar: true,
			t:        5.2750437871662985,
			p:        0.00036019504772583549,
			df:       10,
			ciLo:     1.5402867075557394,
			ciHi:     3.7930466257775963,
			mean1:    10.833333333333334,
			mean2:    8.1666666666666661,
			d:        3.0455479505075256,
			n1:       6, n2: 6,
		},
		// ---- Diverse cases ----
		{
			name:  "minN_both",
			data1: []float64{10, 12}, data2: []float64{8, 9}, equalVar: true,
			t: 2.2360679774997898, p: 0.1548457452714834, df: 2,
			ciLo: -2.3105119936474141, ciHi: 7.310511993647415,
			mean1: 11, mean2: 8.5, d: 2.2360679774997898,
			n1: 2, n2: 2,
		},
		{
			name: "very_imbalanced_welch",
			data1: []float64{50.0, 51.0, 49.5, 50.5},
			data2: []float64{45.1, 46.3, 44.8, 45.9, 46.0, 45.5, 46.2, 45.7, 45.8, 46.4,
				45.6, 45.3, 46.1, 45.4, 45.9, 46.0, 45.7, 45.8, 45.6, 45.5},
			equalVar: false,
			t:        13.495728694065702, p: 0.00039904435608314863, df: 3.4755800963142303,
			ciLo: 3.5320741982640458, ciHi: 5.5079258017359605,
			mean1: 50.25, mean2: 45.729999999999997, d: 8.4168846346010966,
			n1: 4, n2: 20,
		},
		{
			name:  "very_different_variances",
			data1: []float64{10.0, 10.1, 9.9, 10.05, 9.95, 10.02, 9.98},
			data2: []float64{0, 5, -5, 10, -10, 15, -15, 20}, equalVar: false,
			t: 1.7320224356242142, p: 0.12687280738865403, df: 7.0004586654138601,
			ciLo: -2.7391550904737691, ciHi: 17.739155090473766,
			mean1: 10, mean2: 2.5, d: 0.86601299102052487,
			n1: 7, n2: 8,
		},
		{
			name:  "zero_t",
			data1: []float64{10, 11, 9, 12, 8}, data2: []float64{11, 9, 10, 8, 12},
			equalVar: true,
			t:        0, p: 1, df: 8,
			ciLo: -2.3060041352041662, ciHi: 2.3060041352041662,
			mean1: 10, mean2: 10, d: 0,
			n1: 5, n2: 5,
		},
		{
			name:  "cl99_equal_var",
			data1: []float64{101, 102, 100, 103, 99}, data2: []float64{95, 94, 96, 93, 97},
			equalVar: true, cl: 0.99,
			t: 6, p: 0.00032339322188514882, df: 8,
			ciLo: 2.6446126686666052, ciHi: 9.3553873313333948,
			mean1: 101, mean2: 95, d: 3.7947331922020551,
			n1: 5, n2: 5,
		},
		{
			name:  "cl90_welch",
			data1: []float64{8.1, 8.3, 8.0, 8.4}, data2: []float64{7.5, 7.8, 7.2, 7.9, 7.6, 7.7},
			equalVar: false, cl: 0.90,
			t: 4.2759305524706708, p: 0.0028448116309554494, df: 7.8232833739979037,
			ciLo: 0.32890417722942278, ciHi: 0.83776248943724152,
			mean1: 8.1999999999999993, mean2: 7.6166666666666671, d: 2.6765168951565466,
			n1: 4, n2: 6,
		},
		{
			name:  "largeN",
			data1: loadF64s(t, "twoA_largeN_d1"), data2: loadF64s(t, "twoA_largeN_d2"),
			equalVar: true,
			t:        -2.4511553493495439, p: 0.014620921712668798, df: 448,
			ciLo: -2.0929067741471972, ciHi: -0.23025522585279953,
			mean1: 100.672855, mean2: 101.834436, d: -0.23253701408550848,
			n1: 200, n2: 250,
		},
		{
			name:     "huge_magnitude",
			data1:    []float64{1e6, 1.001e6, 0.999e6, 1.0005e6},
			data2:    []float64{1.01e6, 1.011e6, 1.009e6, 1.0105e6},
			equalVar: true,
			t:        -16.561573424216501, p: 3.0904261100621241e-06, df: 6,
			ciLo: -11477.463395819064, ciHi: -8522.5366041809357,
			mean1: 1000125, mean2: 1010125, d: -11.710800875382398,
			n1: 4, n2: 4,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			cl := c.cl
			if cl == 0 {
				cl = 0.95
			}
			d1 := insyra.NewDataList(c.data1)
			d2 := insyra.NewDataList(c.data2)
			r, err := stats.TwoSampleTTest(d1, d2, c.equalVar, cl)
			if err != nil {
				t.Fatalf("TwoSampleTTest error: %v", err)
			}
			if !tEqualOrNaNInf(r.Statistic, c.t, tolStat) {
				t.Errorf("t: got %.17g, want %.17g (Δ=%g)", r.Statistic, c.t, math.Abs(r.Statistic-c.t))
			}
			if !tEqualOrNaNInf(r.PValue, c.p, tolP) {
				t.Errorf("p: got %.17g, want %.17g (Δ=%g)", r.PValue, c.p, math.Abs(r.PValue-c.p))
			}
			if r.DF == nil {
				t.Fatalf("df is nil")
			}
			if !tEqualOrNaNInf(*r.DF, c.df, tolStat) {
				t.Errorf("df: got %.17g, want %.17g", *r.DF, c.df)
			}
			if !tEqualOrNaNInf(r.CI[0], c.ciLo, tolCI) {
				t.Errorf("ci_lo: got %.17g, want %.17g (Δ=%g)", r.CI[0], c.ciLo, math.Abs(r.CI[0]-c.ciLo))
			}
			if !tEqualOrNaNInf(r.CI[1], c.ciHi, tolCI) {
				t.Errorf("ci_hi: got %.17g, want %.17g (Δ=%g)", r.CI[1], c.ciHi, math.Abs(r.CI[1]-c.ciHi))
			}
			if r.Mean == nil || !tEqualOrNaNInf(*r.Mean, c.mean1, tolStat) {
				t.Errorf("mean1: got %v, want %.17g", r.Mean, c.mean1)
			}
			if r.Mean2 == nil || !tEqualOrNaNInf(*r.Mean2, c.mean2, tolStat) {
				t.Errorf("mean2: got %v, want %.17g", r.Mean2, c.mean2)
			}
			if r.N != c.n1 {
				t.Errorf("n1: got %d, want %d", r.N, c.n1)
			}
			if r.N2 == nil || *r.N2 != c.n2 {
				t.Errorf("n2: got %v, want %d", r.N2, c.n2)
			}
			if r.MeanDiff != nil {
				t.Errorf("MeanDiff should be nil for two-sample, got %v", *r.MeanDiff)
			}
			if len(r.EffectSizes) != 1 || r.EffectSizes[0].Type != "cohen_d" {
				t.Fatalf("expected one cohen_d effect size, got %+v", r.EffectSizes)
			}
			if !tEqualOrNaNInf(r.EffectSizes[0].Value, c.d, tolStat) {
				t.Errorf("cohen_d: got %.17g, want %.17g (Δ=%g)",
					r.EffectSizes[0].Value, c.d, math.Abs(r.EffectSizes[0].Value-c.d))
			}
		})
	}
}

type pairedTCase struct {
	name             string
	data1, data2     []float64
	cl               float64 // 0 = use 0.95
	t, p, df         float64
	ciLo, ciHi       float64
	meanDiff, d      float64
	n                int
}

func TestPairedTTest_R(t *testing.T) {
	cases := []pairedTCase{
		{
			name:  "before_after_8pairs",
			data1: []float64{55.0, 48.5, 51.6, 53.2, 50.4, 52.1, 54.0, 56.3},
			data2: []float64{52.2, 45.7, 49.8, 50.9, 47.6, 50.3, 52.1, 53.9},
			t:     14.626443935243289, p: 1.6683518780067002e-06, df: 7,
			ciLo: 1.9491224860059075, ciHi: 2.7008775139940933,
			meanDiff: 2.3250000000000002, d: 5.1712288456276907,
			n: 8,
		},
		// ---- Diverse cases ----
		{
			name:  "minN_2pairs",
			data1: []float64{10, 12}, data2: []float64{8, 9},
			t: 5, p: 0.12566591637800234, df: 1,
			ciLo: -3.8531023680873471, ciHi: 8.8531023680873471,
			meanDiff: 2.5, d: 3.5355339059327373,
			n: 2,
		},
		{
			name:  "negative_meandiff",
			data1: []float64{50, 48, 52, 49, 51}, data2: []float64{53, 50, 54, 51, 53},
			t: -11, p: 0.00038817133849401432, df: 4,
			ciLo: -2.7552890210395589, ciHi: -1.6447109789604413,
			meanDiff: -2.2000000000000002, d: -4.9193495504995379,
			n: 5,
		},
		{
			name:  "some_zero_diffs",
			data1: []float64{10, 11, 12, 13, 14}, data2: []float64{10, 10, 12, 12, 14},
			t: 1.6329931618554523, p: 0.17780780835622115, df: 4,
			ciLo: -0.28008738065825561, ciHi: 1.0800873806582558,
			meanDiff: 0.40000000000000002, d: 0.73029674334022154,
			n: 5,
		},
		{
			name:  "largeN_40",
			data1: loadF64s(t, "pairedA_largeN_a"), data2: loadF64s(t, "pairedA_largeN_b"),
			t:     13.48388522003841, p: 2.8891848936739809e-16, df: 39,
			ciLo: 1.7310086678331182, ciHi: 2.3419913321668822,
			meanDiff: 2.0365000000000002, d: 2.1319894501801024,
			n: 40,
		},
		{
			name:  "cl99",
			data1: []float64{20.1, 19.8, 20.5, 20.0, 19.9, 20.3, 20.2},
			data2: []float64{19.0, 18.5, 19.5, 19.1, 18.8, 19.4, 19.2},
			cl:    0.99,
			t:     19.746564999216762, p: 1.0938117390869697e-06, df: 6,
			ciLo: 0.84706016278386831, ciHi: 1.2386541229304178,
			meanDiff: 1.0428571428571429, d: 7.4635000336714148,
			n: 7,
		},
		{
			name:  "huge_magnitude",
			data1: []float64{1.000000e9, 1.000100e9, 0.999900e9, 1.000050e9, 1.000200e9},
			data2: []float64{1.000080e9, 1.000150e9, 1.000010e9, 1.000180e9, 1.000220e9},
			t:     -3.9295832305070517, p: 0.017109011241689058, df: 4,
			ciLo: -133110.86176370003, ciHi: -22889.138236299979,
			meanDiff: -78000, d: -1.7573630453313984,
			n: 5,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			cl := c.cl
			if cl == 0 {
				cl = 0.95
			}
			d1 := insyra.NewDataList(c.data1)
			d2 := insyra.NewDataList(c.data2)
			r, err := stats.PairedTTest(d1, d2, cl)
			if err != nil {
				t.Fatalf("PairedTTest error: %v", err)
			}
			if !tEqualOrNaNInf(r.Statistic, c.t, tolStat) {
				t.Errorf("t: got %.17g, want %.17g (Δ=%g)", r.Statistic, c.t, math.Abs(r.Statistic-c.t))
			}
			if !tEqualOrNaNInf(r.PValue, c.p, tolP) {
				t.Errorf("p: got %.17g, want %.17g (Δ=%g)", r.PValue, c.p, math.Abs(r.PValue-c.p))
			}
			if r.DF == nil || *r.DF != c.df {
				t.Errorf("df: got %v, want %v", r.DF, c.df)
			}
			if !tEqualOrNaNInf(r.CI[0], c.ciLo, tolCI) {
				t.Errorf("ci_lo: got %.17g, want %.17g (Δ=%g)", r.CI[0], c.ciLo, math.Abs(r.CI[0]-c.ciLo))
			}
			if !tEqualOrNaNInf(r.CI[1], c.ciHi, tolCI) {
				t.Errorf("ci_hi: got %.17g, want %.17g (Δ=%g)", r.CI[1], c.ciHi, math.Abs(r.CI[1]-c.ciHi))
			}
			if r.MeanDiff == nil || !tEqualOrNaNInf(*r.MeanDiff, c.meanDiff, tolStat) {
				t.Errorf("meanDiff: got %v, want %.17g", r.MeanDiff, c.meanDiff)
			}
			if r.N != c.n {
				t.Errorf("n: got %d, want %d", r.N, c.n)
			}
			if r.Mean != nil {
				t.Errorf("Mean should be nil for paired, got %v", *r.Mean)
			}
			if r.Mean2 != nil {
				t.Errorf("Mean2 should be nil for paired, got %v", *r.Mean2)
			}
			if r.N2 != nil {
				t.Errorf("N2 should be nil for paired, got %v", *r.N2)
			}
			if len(r.EffectSizes) != 1 || r.EffectSizes[0].Type != "cohen_d" {
				t.Fatalf("expected one cohen_d effect size, got %+v", r.EffectSizes)
			}
			if !tEqualOrNaNInf(r.EffectSizes[0].Value, c.d, tolStat) {
				t.Errorf("cohen_d: got %.17g, want %.17g (Δ=%g)",
					r.EffectSizes[0].Value, c.d, math.Abs(r.EffectSizes[0].Value-c.d))
			}
		})
	}
}

// Edge case PairedTTest cannot run via R (R rejects all-zero diffs).
// Test that insyra returns NaN/Inf as appropriate for degenerate inputs.
func TestPairedTTest_AllZeroDiff(t *testing.T) {
	a := insyra.NewDataList([]float64{5, 5, 5, 5})
	b := insyra.NewDataList([]float64{5, 5, 5, 5})
	r, err := stats.PairedTTest(a, b, 0.95)
	if err != nil {
		t.Fatalf("PairedTTest error: %v", err)
	}
	// stddev=0, meanDiff=0 → tValue = 0/0 = NaN; effect size = 0/0 = NaN.
	if !math.IsNaN(r.Statistic) {
		t.Errorf("expected NaN t, got %v", r.Statistic)
	}
	if r.MeanDiff == nil || *r.MeanDiff != 0 {
		t.Errorf("expected meanDiff=0, got %v", r.MeanDiff)
	}
	if r.N != 4 {
		t.Errorf("n: got %d, want 4", r.N)
	}
}
