package stats_test

import (
	"math"
	"os"
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/HazelnutParadise/insyra"
	"github.com/HazelnutParadise/insyra/stats"
)

// loadF64sFile parses a labelled comma-separated dump file (first occurrence
// of each label wins). Used for shared rnorm-generated test inputs that are
// generated by an R script alongside the reference values.
type labelledFloats struct {
	once sync.Once
	data map[string][]float64
	path string
}

func (l *labelledFloats) get(t *testing.T, label string) []float64 {
	t.Helper()
	l.once.Do(func() {
		raw, err := os.ReadFile(l.path)
		if err != nil {
			t.Fatalf("read %s: %v", l.path, err)
		}
		l.data = map[string][]float64{}
		for _, line := range strings.Split(string(raw), "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			i := strings.IndexByte(line, ':')
			if i < 0 {
				continue
			}
			name := line[:i]
			parts := strings.Split(line[i+1:], ",")
			vals := make([]float64, 0, len(parts))
			for _, p := range parts {
				p = strings.TrimSpace(p)
				if p == "" {
					continue
				}
				v, err := strconv.ParseFloat(p, 64)
				if err != nil {
					t.Fatalf("parse %s value %q: %v", name, p, err)
				}
				vals = append(vals, v)
			}
			l.data[name] = vals
		}
	})
	v, ok := l.data[label]
	if !ok {
		t.Fatalf("label %q not found in %s", label, l.path)
	}
	return v
}

var zDump = &labelledFloats{path: "testdata/ztest_data_dump.txt"}

// Tolerances. zPValue / zMarginOfError go through gonum's distuv.Normal which
// uses essentially the same algorithm as R's pnorm/qnorm; agreement is at
// machine precision.
const (
	tolZStat = 1e-12
	tolZP    = 1e-12
	tolZCI   = 1e-10
)

func zEqualOrInf(a, b, tol float64) bool {
	if math.IsNaN(a) && math.IsNaN(b) {
		return true
	}
	if math.IsInf(a, 0) && math.IsInf(b, 0) && math.Signbit(a) == math.Signbit(b) {
		return true
	}
	if math.IsNaN(a) != math.IsNaN(b) || math.IsInf(a, 0) != math.IsInf(b, 0) {
		return false
	}
	if b == 0 {
		return math.Abs(a) <= tol
	}
	return math.Abs(a-b) <= tol*math.Max(1, math.Abs(b))
}

type singleZCase struct {
	name        string
	data        []float64
	mu, sigma   float64
	alternative stats.AlternativeHypothesis
	cl          float64 // 0 -> 0.95
	z, p        float64
	ciLo, ciHi  float64
	mean        float64
	n           int
	d           float64
}

func TestSingleSampleZTest_R(t *testing.T) {
	cases := []singleZCase{
		// ---- Existing cases (now checked at full precision) ----
		{
			name: "two_sided_n10", data: []float64{56.96714153011233, 50.61735698828815, 58.47688538100692, 67.23029856408026, 49.658466252766644, 49.6586304305082, 67.79212815507391, 59.67434729152909, 47.30525614065048, 57.42560043585965},
			mu: 50, sigma: 10, alternative: stats.TwoSided,
			z: 2.0493491759488611, p: 0.040427983231365927,
			ciLo: 50.282660793941943, ciHi: 62.678561440033178,
			mean: 56.480611116987561, n: 10, d: 0.64806111169875602,
		},
		{
			name: "greater_n15", data: []float64{47.365823071875376, 47.34270246429743, 54.41962271566034, 32.86719755342202, 34.75082167486967, 46.37712470759027, 41.87168879665576, 55.142473325952736, 42.91975924478789, 37.87696298664709, 66.65648768921554, 49.74223699513465, 52.67528204687924, 37.75251813786544, 46.556172754748175},
			mu: 50, sigma: 10, alternative: stats.Greater,
			z: -1.4377321268093135, p: 0.92474496306201415,
			ciLo: 42.040797808285497, ciHi: math.Inf(1),
			mean: 46.287791611040106, n: 15, d: 0.37122083889598939,
		},
		{
			name: "less_n20", data: []float64{53.10922589709866, 40.490064225776976, 55.75698018345672, 45.99361310081195, 49.083062502067236, 45.98293387770603, 70.52278184508938, 51.86502775262066, 41.422890710440996, 60.225449121031886, 39.791563500289776, 54.08863595004755, 32.403298761202244, 38.71813951101569, 53.96861235869123, 59.38466579995411, 53.7136828118997, 50.843517176117594, 48.98896304410711, 37.214780096325725},
			mu: 50, sigma: 10, alternative: stats.Less,
			z: -0.36743318941094855, p: 0.35664795935351723,
			ciLo: math.Inf(-1), ciHi: 52.856398934188135,
			mean: 49.178394411287563, n: 20, d: 0.082160558871243697,
		},
		{
			name: "two_sided_n25", data: []float64{44.801557916052914, 47.393612290402125, 62.57122226218915, 55.43618289568462, 34.36959844637266, 55.24083969394795, 48.149177195836835, 45.23077999694041, 58.11676288840868, 62.30999522495951, 61.31280119116199, 43.607824767773614, 48.907876241487855, 55.31263431403564, 61.75545127122359, 47.2082576215471, 50.14341023336183, 40.93665025993972, 40.037933759193294, 60.125258223941984, 65.56240028570824, 51.27989878419666, 62.03532897892024, 55.61636025047634, 45.54880245394876},
			mu: 50, sigma: 10, alternative: stats.TwoSided,
			z: 1.0602123489542343, p: 0.28904800432308775,
			ciLo: 48.200496728828362, ciHi: 56.040352666988575,
			mean: 52.120424697908469, n: 25, d: 0.21204246979084687,
		},
		// ---- Diverse cases ----
		{
			name: "minN", data: []float64{50, 52}, mu: 50, sigma: 5, alternative: stats.TwoSided,
			z: 0.28284271247461906, p: 0.77729741078952153,
			ciLo: 44.070480878251615, ciHi: 57.929519121748385,
			mean: 51, n: 2, d: 0.20000000000000001,
		},
		{
			name: "largeN_two_sided", data: zDump.get(t, "zsA_largeN_two"),
			mu: 100, sigma: 10, alternative: stats.TwoSided,
			z: -0.3886902336572115, p: 0.69750530780914299,
			ciLo: 98.33925067565032, ciHi: 101.11105832434968,
			mean: 99.725154500000002, n: 200, d: 0.027484549999999785,
		},
		{
			name: "largeN_greater", data: zDump.get(t, "zsA_largeN_grt"),
			mu: 100, sigma: 10, alternative: stats.Greater,
			z: 1.1053090152642813, p: 0.13451285642505661,
			ciLo: 99.618484346323328, ciHi: math.Inf(1),
			mean: 100.7815715, n: 200, d: 0.078157149999999828,
		},
		{
			name: "largeN_less", data: zDump.get(t, "zsA_largeN_less"),
			mu: 100, sigma: 10, alternative: stats.Less,
			z: -1.2889792945707053, p: 0.098702642484604308,
			ciLo: math.Inf(-1), ciHi: 100.25164115367667,
			mean: 99.088554000000002, n: 200, d: 0.091144599999999798,
		},
		{
			name: "huge_magnitude",
			data: []float64{1.0e9, 1.05e9, 0.97e9, 1.02e9, 0.99e9, 1.01e9},
			mu: 1.0e9, sigma: 5.0e7, alternative: stats.TwoSided,
			z: 0.32659863237108838, p: 0.74397147807505848,
			ciLo: 966659069.36370575, ciHi: 1046674263.9696275,
			mean: 1006666666.6666666, n: 6, d: 0.13333333333333253,
		},
		{
			name: "tiny_magnitude",
			data: []float64{1e-9, 2e-9, 1.5e-9, 0.5e-9, 1.2e-9},
			mu: 0, sigma: 1e-9, alternative: stats.TwoSided,
			z: 2.7727242920997393, p: 0.0055589196270705533,
			ciLo: 3.6347745942341875e-10, ciHi: 2.1165225405765815e-09,
			mean: 1.2400000000000001e-09, n: 5, d: 1.24,
		},
		{
			name: "cl99",
			data: []float64{20.1, 19.8, 20.5, 20.0, 19.9, 20.3, 20.2},
			mu: 20, sigma: 0.5, alternative: stats.TwoSided, cl: 0.99,
			z: 0.60474315681476143, p: 0.54534966801112517,
			ciLo: 19.627499731646921, ciHi: 20.601071696924507,
			mean: 20.114285714285714, n: 7, d: 0.22857142857142776,
		},
		{
			name: "cl90",
			data: []float64{20.1, 19.8, 20.5, 20.0, 19.9, 20.3, 20.2},
			mu: 20, sigma: 0.5, alternative: stats.TwoSided, cl: 0.90,
			z: 0.60474315681476143, p: 0.54534966801112517,
			ciLo: 19.803437597141698, ciHi: 20.425133831429729,
			mean: 20.114285714285714, n: 7, d: 0.22857142857142776,
		},
		{
			name: "zero_z",
			data: []float64{48, 50, 52}, mu: 50, sigma: 5, alternative: stats.TwoSided,
			z: 0, p: 1,
			ciLo: 44.342071329619145, ciHi: 55.657928670380855,
			mean: 50, n: 3, d: 0,
		},
		{
			name: "negative_data_less",
			data: []float64{-5, -2, -6, -3, -4, -7, -1, -3, -5, -4},
			mu: 0, sigma: 5, alternative: stats.Less,
			z: -2.5298221281347035, p: 0.0057060181930008256,
			ciLo: math.Inf(-1), ciHi: -1.3992580606222145,
			mean: -4, n: 10, d: 0.80000000000000004,
		},
		{
			name: "greater_cl99",
			data: []float64{105, 110, 102, 108, 107, 112, 100, 109, 106, 111},
			mu: 100, sigma: 5, alternative: stats.Greater, cl: 0.99,
			z: 4.4271887242357311, p: 4.7734599226689767e-06,
			ciLo: 103.32172104407023, ciHi: math.Inf(1),
			mean: 107, n: 10, d: 1.3999999999999999,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			cl := c.cl
			if cl == 0 {
				cl = 0.95
			}
			dl := insyra.NewDataList(c.data)
			r, err := stats.SingleSampleZTest(dl, c.mu, c.sigma, c.alternative, cl)
			if err != nil {
				t.Fatalf("error: %v", err)
			}
			if !zEqualOrInf(r.Statistic, c.z, tolZStat) {
				t.Errorf("z: got %.17g, want %.17g (Δ=%g)", r.Statistic, c.z, math.Abs(r.Statistic-c.z))
			}
			if !zEqualOrInf(r.PValue, c.p, tolZP) {
				t.Errorf("p: got %.17g, want %.17g (Δ=%g)", r.PValue, c.p, math.Abs(r.PValue-c.p))
			}
			if r.DF != nil {
				t.Errorf("DF must be nil for z-test, got %v", *r.DF)
			}
			if !zEqualOrInf(r.CI[0], c.ciLo, tolZCI) {
				t.Errorf("ci_lo: got %.17g, want %.17g", r.CI[0], c.ciLo)
			}
			if !zEqualOrInf(r.CI[1], c.ciHi, tolZCI) {
				t.Errorf("ci_hi: got %.17g, want %.17g", r.CI[1], c.ciHi)
			}
			if !zEqualOrInf(r.Mean, c.mean, tolZStat) {
				t.Errorf("mean: got %.17g, want %.17g", r.Mean, c.mean)
			}
			if r.Mean2 != nil {
				t.Errorf("Mean2 must be nil for single-sample, got %v", *r.Mean2)
			}
			if r.N != c.n {
				t.Errorf("n: got %d, want %d", r.N, c.n)
			}
			if r.N2 != nil {
				t.Errorf("N2 must be nil for single-sample, got %v", *r.N2)
			}
			if len(r.EffectSizes) != 1 || r.EffectSizes[0].Type != "cohen_d" {
				t.Fatalf("expected one cohen_d effect size, got %+v", r.EffectSizes)
			}
			if !zEqualOrInf(r.EffectSizes[0].Value, c.d, tolZStat) {
				t.Errorf("d: got %.17g, want %.17g", r.EffectSizes[0].Value, c.d)
			}
		})
	}
}

type twoZCase struct {
	name             string
	data1, data2     []float64
	sigma1, sigma2   float64
	alternative      stats.AlternativeHypothesis
	cl               float64 // 0 -> 0.95
	z, p, ciLo, ciHi float64
	mean1, mean2, d  float64
	n1, n2           int
}

func TestTwoSampleZTest_R(t *testing.T) {
	cases := []twoZCase{
		{
			name:  "two_sided_strong",
			data1: []float64{65.97, 47.63, 57.80, 51.74, 63.65, 60.38, 50.41, 58.52, 58.88, 57.38},
			data2: []float64{40.76, 43.83, 42.98, 55.62, 61.43, 53.83, 40.01, 51.52, 48.68, 45.75, 38.06, 50.13},
			sigma1: 10, sigma2: 12, alternative: stats.TwoSided,
			z: 2.0295286858945079, p: 0.042404470252653405,
			ciLo: 0.32628737156034404, ciHi: 18.712379295106327,
			mean1: 57.236000000000004, mean2: 47.716666666666669,
			d: 0.86183994516074824,
			n1: 10, n2: 12,
		},
		{
			name:  "greater",
			data1: []float64{48.93, 66.06, 53.40, 55.11, 56.53, 62.99, 54.89, 51.29, 58.49, 53.33, 58.78, 48.63, 62.46, 52.57, 55.71},
			data2: []float64{40.63, 48.26, 41.43, 42.70, 39.87, 51.94, 44.94, 54.12, 42.10, 49.86, 58.14, 51.30, 38.90, 45.13, 41.72},
			sigma1: 10, sigma2: 12, alternative: stats.Greater,
			z: 2.4485133718729091, p: 0.0071723552648611522,
			ciLo: 3.2413169390249834, ciHi: math.Inf(1),
			mean1: 55.94466666666667, mean2: 46.069333333333333,
			d: 0.89407067075188495,
			n1: 15, n2: 15,
		},
		{
			name:  "less",
			data1: []float64{55.35, 61.14, 61.00, 53.47, 56.38, 56.06, 50.17, 51.50, 61.04, 63.08, 56.49, 48.32, 48.94, 64.49, 45.36, 51.70, 50.22, 54.16, 51.85, 54.18},
			data2: []float64{46.89, 53.49, 47.95, 50.52, 48.51, 53.21, 56.18, 43.75, 40.55, 48.88, 42.79, 42.89, 45.74, 51.65, 44.95, 45.33, 45.52, 55.80, 53.03, 48.86, 45.91, 41.34, 48.97, 43.75, 48.46},
			sigma1: 10, sigma2: 12, alternative: stats.Less,
			z: 2.1181961542679164, p: 0.98292077062134753,
			ciLo: math.Inf(-1), ciHi: 12.343721065297274,
			mean1: 54.744999999999997, mean2: 47.796799999999998,
			d: 0.62906047065262727,
			n1: 20, n2: 25,
		},
		{
			name:  "two_sided_n30",
			data1: []float64{53.11, 52.58, 56.17, 54.85, 59.40, 57.34, 55.61, 49.82, 58.10, 48.55, 47.38, 57.07, 52.47, 54.85, 57.63, 57.76, 50.61, 47.55, 48.85, 59.08, 49.53, 51.87, 54.56, 50.96, 58.01, 57.93, 50.88, 58.08, 53.13, 55.87},
			data2: []float64{48.84, 47.56, 50.28, 53.09, 52.16, 50.62, 55.20, 50.91, 54.53, 51.13, 48.50, 49.15, 51.12, 47.39, 51.50, 46.57, 51.94, 49.06, 54.28, 46.91, 52.21, 52.00, 52.40, 53.57, 49.97, 51.17, 54.51, 45.27, 50.86, 52.99},
			sigma1: 10, sigma2: 12, alternative: stats.TwoSided,
			z: 1.0976308378886557, p: 0.27236572140953486,
			ciLo: -2.4592878591070706, ciHi: 8.719954525773737,
			mean1: 53.986666666666665, mean2: 50.856333333333332,
			d: 0.28340706369509711,
			n1: 30, n2: 30,
		},
		// ---- Diverse cases ----
		{
			name:  "minN_both",
			data1: []float64{50, 52}, data2: []float64{48, 49},
			sigma1: 5, sigma2: 5, alternative: stats.TwoSided,
			z: 0.5, p: 0.61707507745197387,
			ciLo: -7.2998199227002676, ciHi: 12.299819922700268,
			mean1: 51, mean2: 48.5, d: 0.5,
			n1: 2, n2: 2,
		},
		{
			name: "imbalanced_greater",
			data1: []float64{50.0, 51.0, 49.5, 50.5},
			data2: []float64{45.1, 46.3, 44.8, 45.9, 46.0, 45.5, 46.2, 45.7, 45.8, 46.4,
				45.6, 45.3, 46.1, 45.4, 45.9, 46.0, 45.7, 45.8, 45.6, 45.5},
			sigma1: 3, sigma2: 3, alternative: stats.Greater,
			z: 2.7507843999148358, p: 0.002972637933889466,
			ciLo: 1.8172296941734776, ciHi: math.Inf(1),
			mean1: 50.25, mean2: 45.729999999999997,
			d: 1.5066666666666677,
			n1: 4, n2: 20,
		},
		{
			name:  "very_different_sigmas",
			data1: []float64{10.0, 10.1, 9.9, 10.05, 9.95, 10.02, 9.98},
			data2: []float64{0, 5, -5, 10, -10, 15, -15, 20},
			sigma1: 0.5, sigma2: 12, alternative: stats.TwoSided,
			z: 1.7660158213300692, p: 0.077393194581572775,
			ciLo: -0.82366828570049222, ciHi: 15.823668285700492,
			mean1: 10, mean2: 2.5, d: 0.88311721411419553,
			n1: 7, n2: 8,
		},
		{
			name:  "zero_z",
			data1: []float64{10, 11, 9, 12, 8}, data2: []float64{11, 9, 10, 8, 12},
			sigma1: 5, sigma2: 5, alternative: stats.TwoSided,
			z: 0, p: 1,
			ciLo: -6.1979503230456148, ciHi: 6.1979503230456148,
			mean1: 10, mean2: 10, d: 0,
			n1: 5, n2: 5,
		},
		{
			name:  "cl99",
			data1: []float64{101, 102, 100, 103, 99}, data2: []float64{95, 94, 96, 93, 97},
			sigma1: 2, sigma2: 2, alternative: stats.TwoSided, cl: 0.99,
			z: 4.7434164902525691, p: 2.1014359560124403e-06,
			ciLo: 2.7418050147920954, ciHi: 9.2581949852079042,
			mean1: 101, mean2: 95, d: 3,
			n1: 5, n2: 5,
		},
		{
			name:  "cl90_less",
			data1: []float64{8.1, 8.3, 8.0, 8.4}, data2: []float64{7.5, 7.8, 7.2, 7.9, 7.6, 7.7},
			sigma1: 0.5, sigma2: 0.5, alternative: stats.Less, cl: 0.90,
			z: 1.8073922282301242, p: 0.96464942756700822,
			ciLo: math.Inf(-1), ciHi: 0.99695232255502231,
			mean1: 8.1999999999999993, mean2: 7.6166666666666671,
			d: 1.1666666666666643,
			n1: 4, n2: 6,
		},
		{
			name:  "largeN",
			data1: zDump.get(t, "ztA_largeN_d1"), data2: zDump.get(t, "ztA_largeN_d2"),
			sigma1: 5, sigma2: 5, alternative: stats.TwoSided,
			z: -2.3453243085149604, p: 0.019010535803026057,
			ciLo: -2.0421775484568485, ciHi: -0.18279245154316448,
			mean1: 100.672855, mean2: 101.78534000000001,
			d: 0.22249700000000133,
			n1: 200, n2: 250,
		},
		{
			name:     "huge_magnitude_less",
			data1:    []float64{1e6, 1.001e6, 0.999e6, 1.0005e6},
			data2:    []float64{1.01e6, 1.011e6, 1.009e6, 1.0105e6},
			sigma1:   5e3, sigma2: 5e3, alternative: stats.Less,
			z: -2.8284271247461903, p: 0.0023388674905236318,
			ciLo: math.Inf(-1), ciHi: -4184.5642316166341,
			mean1: 1000125, mean2: 1010125, d: 2,
			n1: 4, n2: 4,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			cl := c.cl
			if cl == 0 {
				cl = 0.95
			}
			d1 := insyra.NewDataList(c.data1)
			d2 := insyra.NewDataList(c.data2)
			r, err := stats.TwoSampleZTest(d1, d2, c.sigma1, c.sigma2, c.alternative, cl)
			if err != nil {
				t.Fatalf("error: %v", err)
			}
			if !zEqualOrInf(r.Statistic, c.z, tolZStat) {
				t.Errorf("z: got %.17g, want %.17g (Δ=%g)", r.Statistic, c.z, math.Abs(r.Statistic-c.z))
			}
			if !zEqualOrInf(r.PValue, c.p, tolZP) {
				t.Errorf("p: got %.17g, want %.17g (Δ=%g)", r.PValue, c.p, math.Abs(r.PValue-c.p))
			}
			if r.DF != nil {
				t.Errorf("DF must be nil for z-test, got %v", *r.DF)
			}
			if !zEqualOrInf(r.CI[0], c.ciLo, tolZCI) {
				t.Errorf("ci_lo: got %.17g, want %.17g", r.CI[0], c.ciLo)
			}
			if !zEqualOrInf(r.CI[1], c.ciHi, tolZCI) {
				t.Errorf("ci_hi: got %.17g, want %.17g", r.CI[1], c.ciHi)
			}
			if !zEqualOrInf(r.Mean, c.mean1, tolZStat) {
				t.Errorf("mean1: got %.17g, want %.17g", r.Mean, c.mean1)
			}
			if r.Mean2 == nil || !zEqualOrInf(*r.Mean2, c.mean2, tolZStat) {
				t.Errorf("mean2: got %v, want %.17g", r.Mean2, c.mean2)
			}
			if r.N != c.n1 {
				t.Errorf("n1: got %d, want %d", r.N, c.n1)
			}
			if r.N2 == nil || *r.N2 != c.n2 {
				t.Errorf("n2: got %v, want %d", r.N2, c.n2)
			}
			if len(r.EffectSizes) != 1 || r.EffectSizes[0].Type != "cohen_d" {
				t.Fatalf("expected one cohen_d effect size, got %+v", r.EffectSizes)
			}
			if !zEqualOrInf(r.EffectSizes[0].Value, c.d, tolZStat) {
				t.Errorf("d: got %.17g, want %.17g", r.EffectSizes[0].Value, c.d)
			}
		})
	}
}

// Error-path coverage.
func TestZTest_InvalidInputs(t *testing.T) {
	dl := insyra.NewDataList([]float64{1, 2, 3})
	if _, err := stats.SingleSampleZTest(dl, 0, 0, stats.TwoSided, 0.95); err == nil {
		t.Error("expected error for sigma=0")
	}
	if _, err := stats.SingleSampleZTest(dl, 0, -1, stats.TwoSided, 0.95); err == nil {
		t.Error("expected error for sigma<0")
	}
	if _, err := stats.SingleSampleZTest(dl, 0, 1, stats.AlternativeHypothesis("bogus"), 0.95); err == nil {
		t.Error("expected error for unknown alternative")
	}
	if _, err := stats.SingleSampleZTest(dl, 0, 1, stats.TwoSided, 0); err == nil {
		t.Error("expected error for cl=0")
	}
	if _, err := stats.SingleSampleZTest(dl, 0, 1, stats.TwoSided, 1); err == nil {
		t.Error("expected error for cl=1")
	}

	dl2 := insyra.NewDataList([]float64{1, 2, 3})
	if _, err := stats.TwoSampleZTest(dl, dl2, 0, 1, stats.TwoSided, 0.95); err == nil {
		t.Error("expected error for sigma1=0")
	}
	if _, err := stats.TwoSampleZTest(dl, dl2, 1, -1, stats.TwoSided, 0.95); err == nil {
		t.Error("expected error for sigma2<0")
	}
}
