# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
    - name: Install dependencies
      run: go mod download
    - name: Unit Test
      run: go test -v ./...